### PR TITLE
DrillInfo: fix #20

### LINKED ISSUE #20: Song Title is not saved from Song Constants panel
If the Song Title is set on the "Song Constants" panel, it is saved in-process but _not_ saved to the `.pnd` file.

### PR DESCRIPTION
**Pull request by parker-rho**
Closes #20

Updates the convertToXML method in DrillInfo to also write the song name to the file. Additional steps to implement this include:

 - add the constant 'SONG_NAME' to XMLConstants to reference the song name element
 - update the load method in XMLParser to read and set the song name

@vdye

### CODE REVIEW

**Comment by vdye** [comment]
@parker-rho The tests are failing, likely because your change doesn't handle the case where the Song Name is unset. Please fix that (you can run the tests locally with `mvn test`), amend the commit, and force-push. Please also make sure there's at least one test that _does_ set the Song Name, to ensure that it's exported to the XML and re-imported successfully.

**Review by vdye — CHANGES_REQUESTED** [review]
@parker-rho The tests are failing, likely because your change doesn't handle the case where the Song Name is unset. Please fix that (you can run the tests locally with mvn test), amend the commit, and force-push. Please also make sure there's at least one test that does set the Song Name, to ensure that it's exported to the XML and re-imported successfully.

**Comment by parker-rho** [comment]
All problems should be resolved here :)

**Review by vdye — APPROVED** [review]
Everything looks great, thank you for the updates!

**Pull request merged**
